spring:
  application:
    name: PAYMENT-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url:
    username: sa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    
server:
  port: 9092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka